### ISSUE TITLE
Defining sorting criteria in SortedDictionary

### ISSUE THREAD

**Issue by andreadelfante** [CosmicMind/Algorithm#6]
Is it possible defining a sorting criteria in SortedDictionary? I'm using this data structure but i need to sort elements in order descending directly.

**Comment by daniel-jonathan** [comment]
The SortedDictionary is sorted by its key value. So if you want to access it in descending order, you can access it backwards. For example:

```swift
let n = dict.count
for i in 1..<n {
    let e = dict[n - i]
    // do something with `e`
}
```

Something like that should work. If you need, please reopen the issue. All the best!

**Comment by andreadelfante** [comment]
Yes, I use SortedDictionary.reversed() to get an array of tuple..but i wanna reduce my algorithm complexity, trying to perform only one iteration. It could be useful implementing a custom comparable closure, like TreeMap in Java.

**Comment by daniel-jonathan** [comment]
That is a good idea, I will look into that.

**Comment by daniel-jonathan** [comment]
Here is an issue for your feature request: https://github.com/CosmicMind/Algorithm/issues/7. Thank you!
