### ISSUE TITLE
Xcode 9 build failures

### ISSUE THREAD

**Issue by plu** [CosmicMind/Algorithm#8]
There are some build failures when trying to build with Xcode 9 Beta 2, for example:

* `'Collection' requires the types 'Key' and '(key: Key, value: Value?)' be equivalent`
* `'Sequence' requires the types 'Key' and '(key: Key, value: Value?)' be equivalent`

The project is still set to Swift 3 (3.2).

**Comment by daniel-jonathan** [comment]
Yes, the project is not Swift 4 as that is not publicly released. I only support official releases that are not betas. This will be updated shortly.

**Comment by plu** [comment]
It's not about Swift 4. Xcode 9 is more picky about Swift 3 code. So things that were working before are not compiling anymore.

**Comment by daniel-jonathan** [comment]
Sorry, to be more clear, anything that is used in Xcode 9 will have issues as well as Swift 4.

**Comment by daniel-jonathan** [comment]
I will be updating it soon :) Very soon :)

**Comment by plu** [comment]
Awesome! Thank you :).

**Comment by daniel-jonathan** [comment]
Anytime :)

**Comment by ghost** [comment]
@danieldahan Any time frame on the updates?

**Comment by daniel-jonathan** [comment]
Try the [development](https://github.com/CosmicMind/Algorithm/tree/development) branch :)
